
name: Build firmware
on: push
jobs:
  build:
    runs-on: [ubuntu-latest]
    container: ghcr.io/james-martinez/arduino-cli-esp8266:ff510704
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v1
        with:
          ref: main
      - name: Install neopixel library
        run: arduino-cli lib install "Adafruit NeoPixel"
      - name: Build from source
        run: arduino-cli --config-file /root/.arduino15/arduino-cli.yaml compile -b esp8266:esp8266:d1_mini example/example.ino
      - name: Store binary artifact
        uses: actions/upload-artifact@v2
        with:
          name: Binary
          path: example/build
